name: example
description: "A example Flutter project for the flutter_log_helper package."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_log_helper:
    path: ../
  logger: ^2.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
