include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Do not analyze generated files
    - "**/*.mocks.dart"
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_use_package_imports
    - prefer_single_quotes
